language: python
cache: pip

addons:
  postgresql: "11.2"

services:
  - postgresql

matrix:
  include:
   - env: TOXENV=py37-dj22-waworkflow-postgres
     python: 3.7

   - env: TOXENV=py37-dj30-waworkflow-postgres
     python: 3.7

   - env: TOXENV=py38-dj22-waworkflow-postgres
     python: 3.8

   - env: TOXENV=py37-dj22-waworkflow-sqlite
     python: 3.7

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

install:
  - pip install tox

before_script:
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres

script:
  - tox
