# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from django.db.migrations.recorder import MigrationRecorder
import django.db.models.deletion
from wagtail import VERSION as WAGTAIL_VERSION


def get_revision_model():
    revision_model = "wagtailcore.PageRevision"
    if WAGTAIL_VERSION >= (4, 0, 0):
        try:
            if MigrationRecorder.Migration.objects.filter(
                app="wagtailcore", name="0070_rename_pagerevision_revision"
            ).exists():
                revision_model = "wagtailcore.Revision"
        except (django.db.utils.OperationalError, django.db.utils.ProgrammingError):
            # normally happens when running tests
            pass

    return revision_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        migrations.swappable_dependency(settings.WAGTAILREVIEW_REVIEW_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', editable=False, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_revision', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=get_revision_model())),
                ('submitter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'swappable': 'WAGTAILREVIEW_REVIEW_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('response_token', models.CharField(editable=False, help_text='Secret token this user must supply to be allowed to respond to the review', max_length=32)),
                ('view_token', models.CharField(editable=False, help_text='Secret token this user must supply to be allowed to view the page revision being reviewed', max_length=32)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.WAGTAILREVIEW_REVIEW_MODEL, related_name='reviewers')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
