# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0002_annotation_annotationrange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approve', 'Approved'), ('comment', 'Comment')], default=None, max_length=10)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='wagtail_review.Reviewer')),
            ],
        ),
    ]
