# Generated by Django 2.2.4 on 2019-08-23 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtail_review', '0003_response'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewer',
            unique_together={('review', 'user')},
        ),
    ]
