# Generated by Django 2.1.10 on 2019-07-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0004_remove_token_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationrange',
            name='content_path',
            field=models.TextField(blank=True),
        ),
    ]
