# Generated by Django 2.1.10 on 2019-07-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('wagtail_review', '0005_annotationrange_content_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annotation',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='AnnotationRange',
            new_name='CommentPageLocation',
        ),
        migrations.RenameField(
            model_name='commentpagelocation',
            old_name='annotation',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wagtail_review.Reviewer'),
        ),
        migrations.AlterField(
            model_name='commentpagelocation',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_locations', to='wagtail_review.Comment'),
        ),
    ]
