# Generated by Django 2.2.3 on 2019-07-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0005_migrate_to_new_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationrange',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='response',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='page_revision',
        ),
        migrations.RemoveField(
            model_name='review',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='AnnotationRange',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Reviewer',
        ),
    ]
