# Generated by Django 2.1.10 on 2019-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0006_rename_annotations_to_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='assignees',
            field=models.ManyToManyField(to='wagtail_review.Reviewer', related_name='+'),
        ),
    ]
