# Generated by Django 2.2.3 on 2019-07-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0006_migrate_into_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
