# Generated by Django 2.2.3 on 2019-07-17 17:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtail_review', '0006_delete_old_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Reviewer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='reviewer',
        ),
        migrations.RenameField(
            model_name='commentreply',
            old_name='user',
            new_name='reviewer',
        ),
    ]
