# Generated by Django 2.2.3 on 2019-07-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('wagtail_review', '0007_rename_user_to_reviewer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalUser',
            new_name='ExternalReviewer',
        ),
    ]
