# Generated by Django 2.1.10 on 2019-07-16 13:44

from django.db import migrations


def populate_reviewrequest_assignees(apps, schema_editor):
    Reviewer = apps.get_model('wagtail_review.Reviewer')

    for reviewer in Reviewer.objects.iterator():
        reviewer.review.assignees.add(reviewer)


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0007_review_assignees'),
    ]

    operations = [
        migrations.RunPython(populate_reviewrequest_assignees, migrations.RunPython.noop),
    ]
