# Generated by Django 3.0.3 on 2020-03-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0048_taskstate_finished_by'),
        ('wagtail_review', '0008_rename_externaluser_to_externalreviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalreviewer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='ReviewTaskState',
            fields=[
                ('taskstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.TaskState')),
                ('comment', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtail_review.Reviewer')),
            ],
            bases=('wagtailcore.taskstate',),
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Task')),
                ('reviewers', models.ManyToManyField(to='wagtail_review.Reviewer')),
            ],
            options={
                'verbose_name': 'Review task',
                'verbose_name_plural': 'Review tasks',
            },
            bases=('wagtailcore.task',),
        ),
    ]
