# Generated by Django 2.2.3 on 2019-07-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0008_rename_externaluser_to_externalreviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='review_type',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
