# Generated by Django 2.1.10 on 2019-07-16 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtail_review', '0008_populate_review_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='page_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wagtailreview_comments', to='wagtailcore.PageRevision'),
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.WAGTAILREVIEW_REVIEW_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.WAGTAILREVIEW_REVIEW_MODEL),
        ),
    ]
