# Generated by Django 2.1.10 on 2019-07-16 14:18

from django.db import migrations

def populate_comment_page_revision(apps, schema_editor):
    Comment = apps.get_model('wagtail_review.Comment')

    for comment in Comment.objects.select_related('reviewer', 'reviewer__review').iterator():
        comment.review_id = comment.reviewer.review_id
        comment.page_revision_id = comment.reviewer.review.page_revision_id
        comment.save(update_fields=['review_id', 'page_revision_id'])


def populate_response_review(apps, schema_editor):
    Response = apps.get_model('wagtail_review.Response')

    for response in Response.objects.select_related('reviewer').iterator():
        response.review_id = response.reviewer.review_id
        response.save(update_fields=['review_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0009_decouple_reviewers_1'),
    ]

    operations = [
        migrations.RunPython(populate_response_review, migrations.RunPython.noop),
    ]
