# Generated by Django 3.0.4 on 2020-03-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0010_groupreviewtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupreviewtask',
            options={'verbose_name': 'Group review task', 'verbose_name_plural': 'Group review tasks'},
        ),
    ]
