# Generated by Django 2.1.10 on 2019-07-16 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0010_decouple_reviewers_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagtailreview_comments', to='wagtailcore.PageRevision'),
        ),
        migrations.AlterField(
            model_name='response',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.WAGTAILREVIEW_REVIEW_MODEL),
        ),
    ]
