# Generated by Django 2.1.10 on 2019-07-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtail_review', '0011_decouple_reviewers_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagtailreview_shares', to='wagtailcore.Page')),
            ],
        ),
        migrations.AddField(
            model_name='reviewer',
            name='share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtail_review.Share'),
        ),
    ]
