# Generated by Django 3.0.7 on 2020-06-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0011_groupreviewtask_meta'),
    ]

    run_before = [
        ('wagtailcore', '0051_taskstate_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewtaskstate',
            old_name='comment',
            new_name='review_comment',
        ),
    ]
