# Generated by Django 2.1.10 on 2019-07-16 14:38

from django.db import migrations


def populate_share(apps, schema_editor):
    Reviewer = apps.get_model('wagtail_review.Reviewer')
    Share = apps.get_model('wagtail_review.Share')

    for reviewer in Reviewer.objects.exclude(email='').select_related('review', 'review__page_revision').iterator():
        Share.objects.get_or_create(
            page_id=reviewer.review.page_revision.page_id,
            email=reviewer.email,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0012_share'),
    ]

    operations = [
        migrations.RunPython(populate_share, migrations.RunPython.noop),
    ]
