# Generated by Django 3.0.7 on 2020-06-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0013_populate_new_comment_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewtaskstate',
            name='review_comment',
        ),
    ]
