# Generated by Django 2.1.10 on 2019-07-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_review', '0013_populate_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='review',
        ),
    ]
